### ISSUE TITLE
get_measures outputs

### ISSUE THREAD

**Issue by gdauby** [TiagoOlivoto/pliman#3]
I have some difficulty to interpret the outputs of the `get_measures` function data.frame.

For example, what are the differences between diam_max, major_axis and length ?

Likewise, differences between diam_min, minor_axis and width ?

I assume some of these measures refers to the best-fitted ellipse ?

Perhaps explanations are somewhere in the online documentation and I missed it.

Thanks for the clarification.

**Comment by TiagoOlivoto** [comment]
Hi.
You'll find some details in the [online documentation](https://tiagoolivoto.github.io/pliman/reference/analyze_objects.html#value). Please, don't hesitate to email me if you have any questions 

Please, only open an issue if you find a clear bug in the code. To ask for specific questions about package functionality you can send an email to the developers or ask in forums like Stack Overflow. 
Since this is not a bug, I'm closing this now
