### ISSUE TITLE
issue on image_crop for the CRAN version

### ISSUE THREAD

**Issue by gdauby** [TiagoOlivoto/pliman#4]
Dear Tiago,

thanks for previous answers to my questions (and for this great package).

I have an issue that only appears on the version on CRAN using the `image_crop ` function. I have myself the developement version which does not have this issue. I tried to instal the development version for one of my student but it did no work the reason why I installed the CRAN version.

In any case, here the line of code that provide an error :

```
pliman::image_crop(leaves,
                       plot = TRUE)
```
After selecting the two points on the plot to crop the image, he gets this error.

> Error in image@.Data[w, h, ] : only 0's may be mixed with negative subscripts

I dont know whether this is because he is using the CRAN version. 
But when trying to install the development version from gihtub,  I have the following error

`devtools::install_github("TiagoOlivoto/pliman")`

> Downloading GitHub repo TiagoOlivoto/pliman@HEAD
> Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
>   download from 'https://api.github.com/repos/TiagoOlivoto/pliman/tarball/HEAD' failed

Attached is the image that causes the error but it seems to be the case for all images.
![PH_1](https://github.com/TiagoOlivoto/pliman/assets/7722785/ec8a6937-c546-42bb-829f-adb2cf302bd7)

**Comment by TiagoOlivoto** [comment]
Hi, as you said, this issue was fixed on the development version. So, I cannot do anything to help you here.

The correct way to open an issue is first to check if that issue was not already solved in the dev version. If no, provide a minimal example and inform what you were expecting if it was working. In this case, the correct way is to ask about the error when downloading pliman from github in right places. For example, if you google for "Error in utils::download.file(url, path, method = method, quiet = quiet, :", you'll find some solutions like [this ](https://github.com/forestgeo/learn/issues/102#issuecomment-524264784) or [this](https://support.posit.co/hc/en-us/articles/206827897-Secure-Package-Downloads-for-R) 

It seems to be a problem with the secure download method for HTTP or internet connection.
Good luck!
